version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ci/Dockerfile
      args:
        app_name: policy-machine
        app_version: latest
    ports:
      - "8080:8080"
    environment:
      - OPA_URL=http://opa:8181
    depends_on:
      - opa
    networks:
      - policy-network

  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    command: >
      run --server
      --addr=0.0.0.0:8181
      --config-file=/config/config.yaml
      --watch
      /policies
    volumes:
      - ./opa:/config
      - ./opa/policies:/policies
    networks:
      - policy-network

networks:
  policy-network:
    driver: bridge
